### ISSUE TITLE
Site is down, can't install

### ISSUE THREAD

**Issue by katsacca** [UmbrellaRE/ToolKitV#2]
When trying to install the program, it fails to load because your website is down. 

do you have a way to install completely locally?

**Comment by VojtaNN** [comment]
I have same problem as you bro
![Snímek obrazovky 2022-07-27 170525](https://user-images.githubusercontent.com/61760213/181282487-cb7a34de-3409-4bbd-9ef6-49286f0e7cda.png)
😢

**Comment by DurtyFree** [comment]
I have provided a working package in issue #4
