### ISSUE TITLE
[PLEASE FIX] Toolkit Down

### ISSUE THREAD

**Issue by meistroburger** [UmbrellaRE/ToolKitV#3]
Please fix the website so the toolkit works again! I love the toolkit!

**Comment by ventraks** [comment]
https://github.com/UmbrellaRE/ToolKitV/releases/tag/v1.0.0

**Comment by cedriclmao** [comment]
> https://github.com/UmbrellaRE/ToolKitV/releases/tag/v1.0.0

I downloaded the .exe there and it still does not work

**Comment by DurtyFree** [comment]
I have provided a working package in issue #4
