### ISSUE TITLE
ToolKitV not starting / Website down => Download here

### ISSUE THREAD

**Issue by DurtyFree** [UmbrellaRE/ToolKitV#4]
As many people seem to have issues with the tool not starting up, due to the auto updater failing to reach the website, I have uploaded a compiled and working version of it here

Feel free to download it - nothing is changed, its just the compiled state of this repository
[ToolKitV.zip](https://github.com/UmbrellaRE/ToolKitV/files/9583442/ToolKitV.zip)

**Comment by vastie** [comment]
Not working for me :(

**Comment by Vinipux322** [comment]
@vastie download new release and drop it to `C:\Users\%UserName%\AppData\Local\ToolKitV` folder
